"""Update user role to support multiple roles

Revision ID: 29bbe7701912
Revises: 
Create Date: 2025-11-21 19:52:21.172331

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '29bbe7701912'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Enum('ALUMNO', 'ADMINISTRATIVO', 'DIRECTOR', 'SUPERADMIN', name='userrole'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('ALUMNO', 'ADMINISTRATIVO', 'DIRECTOR', 'SUPERADMIN', name='userrole'),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
