"""empty message

Revision ID: ef876c5b1ba0
Revises: 29bbe7701912
Create Date: 2025-11-21 21:20:03.030236

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ef876c5b1ba0'
down_revision = '29bbe7701912'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('ALUMNO', 'ADMINISTRATIVO', 'DIRECTOR', 'SUPERADMIN'),
               type_=sa.String(length=15),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=15),
               type_=mysql.ENUM('ALUMNO', 'ADMINISTRATIVO', 'DIRECTOR', 'SUPERADMIN'),
               existing_nullable=False)

    # ### end Alembic commands ###
